#!/bin/bash
set -e

assembler=$1
if [ -z "$assembler" ]; then
  echo "Please specify the assembler command to use, for instance nasm or yasm."
  exit 1
fi

#Add leading underscore to match macOS calling convention.
sed 's/Java_JNIArraySum_computeNativeArraySum/_Java_JNIArraySum_computeNativeArraySum/g' ArraySum.asm > ArraySumMac.asm
$assembler -f macho64 -o ArraySum.o ArraySumMac.asm
clang -shared -o libArraySum.so ArraySum.o
rm ArraySum.o ArraySumMac.asm
javac JNIArraySum.java
